//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeOrganizer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeRecord
    {
        public int Id { get; set; }
        public string title { get; set; }
        public int numberOfEpisodes { get; set; }
        public Nullable<int> rating { get; set; }
        public string description { get; set; }
        public System.DateTimeOffset lastUpdate { get; set; }
        public Nullable<int> year { get; set; }
        public string season { get; set; }
    }
}
